# artifacts are by-product produced during the development process - in this case when unzipping dataset it will create more files
# not necessary to create config.yaml file but helps to prevent hardcoding values and make it easier to update configurations in the future
# yaml is just a lot cleaner than json and xml
artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion